const { assert } = require('chai')
const { Script, Ops } = require('../index')


let script1, script2;
before(() => {
  script1 = new Script([
    Ops.OP_FALSE,
    Ops.OP_RETURN,
    'hello',
    'world'
  ])

  script2 = new Script([
    Ops.OP_DUP,
    Ops.OP_HASH160,
    [106, 252, 13, 107, 181, 120, 40, 42, 192, 246, 173, 92, 90, 242, 41, 76, 25, 113, 33, 8],
    Ops.OP_EQUALVERIFY,
    Ops.OP_CHECKSIG
  ])
})


describe('new Script()', () => {
  it('must instantiate a new script', () => {
    const script = new Script()
    assert.instanceOf(script, Script)
    assert.lengthOf(script.chunks, 0)
  })

  it('must instantiate a new script with chunks', () => {
    assert.instanceOf(script1, Script)
    assert.lengthOf(script1.chunks, 4)
  })
})


describe('Script#fromHex()', () => {
  it('must parse a script from the hex string', () => {
    const script = Script.fromHex('76a9146afc0d6bb578282ac0f6ad5c5af2294c1971210888ac')
    assert.instanceOf(script, Script)
    assert.lengthOf(script.chunks, 5)
    assert.equal(script.chunks[1].op, 'OP_HASH160')
    assert.equal(script.chunks[4].op, 'OP_CHECKSIG')
  })
})


describe('Script#toBuffer()', () => {
  it('must return a data buffer', () => {
    const buf = script2.toBuffer()
    assert.instanceOf(buf, Buffer)
    assert.lengthOf(buf, 25)
  })
})


describe('Script#toHex()', () => {
  it('must return a hex string', () => {
    const hex = script2.toHex()
    assert.equal(hex, '76a9146afc0d6bb578282ac0f6ad5c5af2294c1971210888ac')
  })
})


describe('Script serializing and parsing round trip', () => {
  let b512, b66000;

  before(() => {
    b512 = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sodales id mi eget bibendum. Quisque eget dui tellus. Curabitur rutrum molestie massa, faucibus tempor metus vulputate euismod. Nam porttitor lorem vel nulla euismod facilisis. Ut ac ultrices nunc. Suspendisse elementum ut urna vel commodo. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla vitae sem nec purus euismod posuere non ac nisl. Curabitur id finibus quam. Nulla ultrices sollicitudin massa amet.'
    b66000 = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam orci magna, condimentum ac tellus consequat, malesuada suscipit arcu. Nunc fermentum sem id est mattis, ut maximus eros pellentesque. Etiam in finibus neque. Proin in ornare ante, et consequat lorem. Vestibulum in venenatis orci. Curabitur vitae hendrerit leo, quis rutrum arcu. Fusce ac scelerisque mi. Etiam suscipit nisi et nibh vehicula, at interdum purus gravida. Nam nisi lectus, cursus at nibh vitae, lacinia facilisis lorem.
Nulla mattis rhoncus urna at dignissim. Aliquam sit amet tortor et ipsum gravida dapibus sit amet sit amet nulla. Suspendisse ut tortor ullamcorper, placerat quam vel, laoreet leo. Integer nisi sapien, imperdiet non tristique quis, elementum non turpis. Aliquam suscipit sapien eu pharetra pulvinar. Sed nec massa dapibus, efficitur nulla vitae, tempor risus. Fusce sed mollis massa, eu vulputate lorem. Morbi eget pellentesque nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc condimentum nulla justo, a ullamcorper ante sagittis sed.
Vestibulum imperdiet justo non mauris sollicitudin eleifend. Curabitur porta congue dolor, a pharetra odio facilisis a. Nullam eget lectus ac nibh gravida pulvinar id nec tellus. Praesent pretium ex dignissim mattis tempus. Ut sollicitudin ligula posuere, porta quam nec, cursus leo. Curabitur fringilla accumsan tempor. In sed pharetra ipsum. Ut suscipit urna non neque sodales lobortis. Etiam posuere elementum dolor sit amet ullamcorper. Curabitur vitae diam at lacus luctus faucibus. Phasellus porttitor eros ut velit convallis imperdiet non vitae tellus.
Etiam sit amet ex risus. Praesent porta tristique nisl, at convallis mauris commodo et. Aenean sit amet fringilla massa, sit amet congue felis. Praesent neque odio, aliquet at feugiat ut, cursus in eros. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse semper libero non urna blandit faucibus. Aenean congue varius dui, in sagittis orci volutpat quis. Proin efficitur viverra sem at tempor. Nunc varius nec ligula in eleifend. Fusce pulvinar non ipsum ut venenatis. Vivamus posuere dictum leo, laoreet scelerisque diam maximus eu. Vestibulum tristique et velit in rhoncus. Nullam viverra, felis a ornare ultricies, ipsum nunc accumsan tortor, consectetur vehicula dolor urna non neque. Pellentesque pharetra elit nec auctor volutpat. Sed eu felis a turpis ullamcorper cursus. Quisque vitae venenatis nisl.
Ut eget convallis risus. Integer id condimentum urna. Fusce sit amet enim urna. Nullam pellentesque sed mauris at eleifend. Sed rhoncus sem ac dui molestie, ut venenatis neque varius. Morbi et varius enim. Sed est turpis, posuere ut porttitor sit amet, sagittis eu augue. Suspendisse ac dolor vel nunc varius vulputate. Ut fringilla sapien lorem, vitae convallis tortor sagittis vitae. Praesent viverra ac lorem at pulvinar. Nam nisi metus, commodo quis nunc eget, dictum auctor metus. Quisque mattis lacus ac ligula dictum efficitur eget et justo. Quisque luctus faucibus tellus, nec gravida felis interdum vel. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed tortor nibh, pretium ut quam at, posuere viverra arcu.
In mattis augue ut imperdiet mattis. Integer feugiat sapien non consectetur sodales. Nulla interdum orci et pulvinar mattis. Donec sit amet bibendum turpis, vel faucibus elit. Donec tristique lectus ligula, ac lobortis magna euismod sit amet. Nam ullamcorper auctor nisl. Etiam ipsum tellus, sagittis in mauris sagittis, euismod ultrices nisl. Donec fermentum dui vitae orci vestibulum molestie. Nunc sed molestie libero, eget tempor dolor. Nulla facilisi. Nunc eget metus fringilla, tempor erat vitae, luctus mi. Mauris ornare sapien est, at interdum erat venenatis ut. Morbi varius ut felis ac aliquam. Curabitur ornare tellus quis massa interdum, non dictum augue hendrerit.
Quisque in facilisis libero. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin aliquet, leo eget auctor lobortis, augue ipsum varius ex, ut mollis lectus neque eget nunc. Nulla facilisi. Proin sit amet purus feugiat, mollis tortor ut, dictum tortor. Cras a nisi sed nisi condimentum dictum id vel turpis. Fusce mattis, nisl sit amet tincidunt porttitor, diam magna placerat eros, in euismod magna metus quis urna. In sodales vulputate placerat. Quisque lectus libero, mollis in massa eu, tempor faucibus nunc. Proin posuere ipsum quis dignissim lobortis. Mauris tempus neque id posuere scelerisque. Donec quis elit urna.
Sed eu cursus massa, quis maximus libero. Suspendisse sed interdum nisl, ut rhoncus felis. Sed sed viverra velit. Nullam vehicula, eros ac dapibus dictum, mauris turpis vestibulum leo, eu dapibus ante justo et ex. Nulla gravida tellus sed leo congue, id cursus turpis imperdiet. Nullam ullamcorper eu tellus commodo euismod. Sed ullamcorper vehicula nulla quis commodo. Duis nulla ex, euismod vel nunc a, maximus mollis urna. Vestibulum eu gravida arcu. Ut ut efficitur urna. Nulla vel scelerisque odio, vitae aliquet leo. Proin consectetur accumsan leo, id auctor dolor porta in. Cras pulvinar vulputate nisl, vitae luctus justo fringilla sed. Sed rhoncus interdum velit ut tempor.
Donec sollicitudin eget sem a posuere. Aliquam tortor velit, varius in pulvinar in, lacinia eu mauris. Vivamus dapibus, magna non lobortis vehicula, leo ante lacinia est, vitae ultricies ligula metus ac felis. Mauris efficitur malesuada quam, nec ultrices eros sodales elementum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur in dolor velit. Quisque vel mauris malesuada, ultricies leo sed, tempor urna. Vivamus convallis risus eu feugiat pulvinar. Fusce posuere, metus eu rutrum scelerisque, dolor sem tincidunt velit, ut venenatis sapien augue sed purus. Donec vel libero augue. Duis eu neque libero.
Nullam quam orci, venenatis eget erat tempor, accumsan pretium est. Aliquam condimentum, dui eu sagittis dignissim, urna orci lobortis tellus, quis aliquet purus sem eu ex. Curabitur sit amet ipsum eu sapien tempor condimentum eu id lacus. Mauris posuere aliquam tellus, et posuere odio rhoncus sed. Fusce ornare augue vitae nulla malesuada, sed finibus lacus egestas. Nullam sagittis ipsum ante, nec porta dolor porttitor nec. Suspendisse elit velit, sodales non fringilla in, porta bibendum purus. Curabitur eu urna in augue volutpat lobortis.
Etiam semper libero non erat laoreet, a fermentum ligula pretium. In eleifend finibus magna, eget porta lectus fermentum non. Praesent elementum cursus neque, nec aliquet est interdum consectetur. Vivamus enim orci, lacinia sit amet viverra eu, dapibus et nisl. Morbi convallis justo eget viverra vulputate. Cras massa nibh, viverra quis efficitur varius, consequat sed massa. Etiam in purus ut magna blandit elementum vel sit amet magna. Nam fermentum rhoncus bibendum. Fusce finibus vestibulum augue, ac pharetra massa efficitur dignissim. Nunc ligula nibh, gravida in turpis at, volutpat molestie metus.
Donec eget lorem et felis vehicula mattis. Mauris quam ipsum, ultrices eget ipsum quis, luctus suscipit metus. Cras porta arcu quis pretium volutpat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent viverra vestibulum sapien, et posuere tellus ultrices sit amet. Nam bibendum velit nec nulla tempus, nec aliquam justo euismod. In nisl ex, aliquet vitae vulputate a, consequat sodales mauris. Proin in tincidunt tellus. Vivamus eu nunc sed ipsum ornare efficitur. Ut efficitur eros est, ut rutrum nisl pulvinar et. Nunc eu magna finibus, feugiat lacus quis, cursus erat. Morbi non ornare lacus. Duis vel dolor diam. In mollis ac velit quis euismod.
Maecenas risus diam, auctor eu consectetur vitae, pharetra nec ligula. Quisque porttitor ullamcorper felis eget pharetra. Vestibulum ex leo, iaculis et eros id, vestibulum blandit ipsum. Nulla sem leo, pretium vitae nulla ac, posuere ultricies tortor. Quisque dapibus, nulla sagittis viverra hendrerit, orci massa imperdiet felis, vitae dapibus leo diam quis purus. Aliquam et pharetra nisl, eu ornare ante. Pellentesque eget sapien mattis, condimentum orci ut, posuere eros. Mauris efficitur blandit urna vitae sagittis. Proin posuere sollicitudin aliquet. Etiam eget dolor eu lacus interdum condimentum id id dolor. Aenean euismod, justo mattis laoreet eleifend, mi augue facilisis orci, quis pharetra sem enim eu ex. Phasellus sed mattis velit, quis maximus neque. Nunc semper ullamcorper ultrices.
In diam magna, mattis in porttitor hendrerit, tempus vitae velit. Nullam ac sem convallis, placerat neque vitae, commodo magna. Integer fringilla vestibulum turpis. Aenean sit amet feugiat eros. Maecenas interdum tellus eget maximus rutrum. Sed varius, libero sit amet iaculis gravida, mi dui fermentum ligula, vel vulputate ante massa sit amet leo. Phasellus massa tortor, gravida eget cursus vitae, laoreet a arcu.
Mauris et nunc at dui dapibus egestas pretium eu orci. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut fringilla eu turpis vitae aliquam. Vivamus in tristique nunc. Vestibulum venenatis mauris quis quam mollis sollicitudin. Etiam nec tellus molestie, ultricies lacus vitae, dignissim lorem. Aliquam sodales condimentum neque. Suspendisse vitae purus ac turpis feugiat facilisis sed non arcu. Vestibulum tincidunt rutrum pellentesque.
Sed in sem ac eros cursus vulputate. Aliquam erat volutpat. Nulla eu facilisis lorem. Curabitur ipsum tellus, commodo sed nisl in, blandit varius orci. Integer in cursus nisi. In enim augue, fermentum eget eros ac, fermentum molestie felis. Aenean cursus eu felis eget porta. Nulla blandit eros libero, vel volutpat nunc aliquam sit amet. Fusce metus libero, sollicitudin quis accumsan a, egestas in felis. Mauris molestie porta enim, a rutrum quam lobortis nec.
Nulla facilisi. Aenean lobortis fermentum commodo. Donec vel tristique dolor, vel lacinia turpis. Maecenas est nunc, interdum quis metus malesuada, placerat porta dui. Sed maximus laoreet magna quis congue. Pellentesque enim felis, blandit id arcu vel, auctor interdum est. In ornare laoreet rhoncus.
Donec molestie, nulla vitae rhoncus tincidunt, nulla nisl imperdiet justo, eu fringilla risus nulla non tellus. Cras aliquam ligula arcu, tristique aliquam lectus vehicula vitae. Suspendisse congue, nulla efficitur vulputate porta, magna nunc mattis arcu, id consequat tortor justo vitae arcu. Nulla facilisi. Nulla a nunc feugiat, imperdiet felis non, mattis lorem. Cras accumsan in augue nec vehicula. Nullam ac leo rhoncus, tempus lacus blandit, tempus mi. Curabitur vulputate condimentum massa id laoreet. Morbi pharetra, est ac aliquet vestibulum, purus justo porta lorem, eu tristique felis nulla mattis turpis. Nullam nibh quam, malesuada a viverra ut, interdum eget nibh. Cras non sollicitudin velit. Morbi egestas scelerisque dignissim.
In in ligula interdum, bibendum neque at, eleifend augue. Donec nisi turpis, rutrum nec mauris non, lobortis laoreet ipsum. In pulvinar placerat orci et laoreet. Aliquam urna eros, vestibulum vitae ultricies ac, interdum ut tortor. Aliquam erat volutpat. Sed et lacinia ligula. Sed semper aliquet metus, a tempus ante accumsan eget. Integer sit amet dapibus mauris. Vivamus feugiat commodo hendrerit. In pulvinar suscipit felis sed sodales. Fusce pretium lorem orci, vel gravida velit maximus molestie.
Nunc sed congue urna. Vivamus ut nisl non magna condimentum feugiat at vitae sapien. Quisque dapibus mattis libero nec faucibus. Nulla id eleifend nibh, in tempor sapien. Cras lectus eros, efficitur id lacus vel, eleifend tincidunt metus. Vivamus vitae congue magna. Donec vitae metus ac nisl auctor rhoncus. Cras a odio consectetur, malesuada velit sed, efficitur elit. Fusce vel aliquam velit. Praesent sollicitudin dui cursus, ultrices dolor vitae, sollicitudin enim. Suspendisse accumsan rhoncus turpis non varius. Sed luctus sit amet urna nec gravida. Morbi id hendrerit felis.
Integer egestas hendrerit lorem, vitae faucibus lorem accumsan eu. In hac habitasse platea dictumst. In hac habitasse platea dictumst. Nunc sit amet turpis vitae mauris efficitur suscipit. Aliquam nunc orci, venenatis sit amet pulvinar gravida, dictum nec libero. Aliquam varius ornare neque nec hendrerit. Curabitur elementum, erat at mollis consequat, leo nisl pharetra tellus, et hendrerit tellus nibh id metus. Cras dictum quis elit sed convallis. Praesent porta nisi ante, non semper mi ultricies in. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi pellentesque tincidunt odio ut mattis. Ut velit mauris, faucibus ac egestas blandit, pellentesque vel velit. Integer mauris enim, tincidunt tempor placerat et, lobortis vel arcu.
Maecenas quis nisl ultricies, commodo diam a, ullamcorper elit. In a aliquam magna, efficitur congue erat. Phasellus et vestibulum nulla. Cras molestie ante at tristique placerat. Cras rutrum posuere turpis quis blandit. Integer bibendum, mauris eu dignissim porttitor, tortor tortor imperdiet mauris, id cursus sem arcu eget tellus. Phasellus cursus urna libero, nec elementum ipsum porta ac. Donec nec varius nisl. Quisque tempor gravida dolor, et lacinia magna venenatis ut. Donec luctus feugiat arcu vitae faucibus. Ut finibus neque sit amet eros ultrices, sed scelerisque risus pellentesque. Pellentesque consequat, neque vitae efficitur suscipit, enim sapien fringilla libero, sit amet aliquam lectus metus in ante. Phasellus ante tellus, varius a erat eu, sodales sollicitudin tellus. Sed vel facilisis tellus.
Fusce efficitur venenatis risus eu cursus. Fusce a dapibus lacus, id accumsan est. Praesent ac dignissim ex, a ultrices felis. Nunc vitae eleifend nisi. Quisque pellentesque malesuada nisl. Vestibulum eget convallis mi, ac iaculis eros. Praesent sagittis, felis at tristique tincidunt, neque nibh vehicula tellus, eget convallis justo orci at purus. Integer ultrices, nisl id vehicula efficitur, neque tellus aliquam nisl, ac sodales sem lacus a risus. Morbi dapibus sem vitae nunc pulvinar, id hendrerit tellus pharetra. Donec quis purus odio. Morbi consectetur porttitor ante, eget venenatis velit fringilla et. Vivamus elementum quam vel interdum mattis. Fusce sit amet cursus nisl, ac finibus neque. Sed vel turpis in metus mattis faucibus.
Mauris scelerisque tempus quam, sagittis interdum eros tincidunt et. Fusce at condimentum dui, a ultrices risus. In euismod arcu nisi. Mauris lobortis eu leo quis aliquam. Morbi hendrerit semper odio sit amet semper. Integer ultricies ligula quis euismod dapibus. Mauris tempus est quis arcu sodales vulputate. Cras odio lectus, gravida sit amet velit eget, malesuada commodo odio. Vivamus scelerisque scelerisque leo, sed aliquam ipsum mollis nec. Proin commodo, libero eu feugiat faucibus, lectus lacus dapibus magna, at maximus tellus est quis purus. Maecenas imperdiet suscipit rhoncus. Fusce ut sem elit. Etiam ullamcorper ex ut turpis vestibulum, vel tincidunt ipsum malesuada. Vivamus ac ligula at mi hendrerit vestibulum. Etiam nec neque pellentesque, fermentum lorem eu, congue risus. Maecenas efficitur accumsan tortor eget ornare.
Etiam laoreet ac mauris sit amet interdum. Suspendisse potenti. Integer vitae dapibus leo. Duis quis tincidunt lectus, ut scelerisque ligula. Suspendisse potenti. Praesent risus sapien, molestie vel sodales et, sagittis non lectus. Praesent vel congue dolor, eget convallis dolor. Sed a egestas risus. Etiam id turpis feugiat, efficitur lectus et, ornare nisi. Aenean dictum hendrerit semper. Proin tincidunt risus non mauris convallis, eu ultrices libero accumsan. Etiam ligula ex, blandit a lacus sed, euismod commodo enim.
Fusce id iaculis diam. Ut lectus justo, placerat a tellus ac, iaculis suscipit nunc. Cras ac eleifend leo. Maecenas viverra tincidunt vestibulum. Nullam aliquet mollis erat, ac dictum nisi volutpat at. Quisque a rhoncus odio. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
Duis vel dolor in velit pellentesque efficitur. Maecenas facilisis sodales lorem, nec egestas sapien pulvinar in. Vestibulum accumsan mauris tincidunt, bibendum nisl non, sagittis sapien. Vivamus ut mi neque. Etiam vitae feugiat augue. Nulla viverra dolor nec sem lacinia sagittis sit amet eget odio. In elit metus, sollicitudin et velit et, consectetur commodo enim. Donec vitae feugiat turpis. Cras pellentesque, erat id semper sollicitudin, quam est cursus nisl, ac laoreet ex turpis eget ante. Maecenas eget fermentum metus.
Vestibulum in lectus eu quam scelerisque sollicitudin. Aliquam et velit et odio hendrerit fermentum. Nunc id elit et libero ultricies malesuada. Donec imperdiet quis urna vitae tempus. Vivamus at efficitur diam. Proin consequat dolor purus, et posuere mauris cursus id. Nam suscipit, risus et iaculis condimentum, est risus vestibulum tellus, nec bibendum elit mi non orci. Proin ac elit nisi. Quisque malesuada volutpat elementum. Praesent sem leo, lobortis ac tellus sit amet, lobortis viverra risus. Aenean a ipsum sodales, lobortis nulla eget, tempor justo. Proin pretium lobortis risus. Sed elementum odio vitae fermentum tincidunt.
Vestibulum vel feugiat quam, id dapibus orci. Suspendisse a mi urna. Ut mattis, mauris sit amet vehicula porttitor, erat ante bibendum libero, ut tempor elit elit at libero. Mauris ullamcorper commodo sem vitae tincidunt. Vestibulum egestas felis mi, eu tempor ligula ullamcorper in. Donec hendrerit, erat vitae eleifend mattis, velit velit pulvinar mi, vel gravida risus nulla id urna. Aenean ut dolor vulputate, posuere arcu a, porttitor velit.
Nullam sed euismod magna. Vestibulum urna lectus, aliquet consequat gravida eget, molestie non elit. Etiam ultrices id est a fringilla. Aliquam ac mi nisi. Integer euismod volutpat tempus. Curabitur urna nulla, blandit vitae leo eu, cursus tincidunt lectus. Mauris tempor, nibh ac ultricies dignissim, nisi nibh venenatis neque, eget mollis nisl nulla quis nisi. Vestibulum nec blandit risus, ut mattis nisl.
Fusce at orci et sapien venenatis molestie. Suspendisse tincidunt semper eros quis accumsan. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam lorem felis, dictum ac aliquet ut, lacinia in sem. Suspendisse suscipit quam non justo pretium pulvinar. Aenean mattis leo libero, quis posuere est ultrices in. In maximus dolor purus, vel viverra arcu aliquam auctor. Sed id imperdiet nibh, fermentum convallis metus. Aenean sodales felis nec justo vestibulum, commodo porttitor felis imperdiet. Nam in mauris lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam pulvinar nisi mi. Integer molestie accumsan dapibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Vestibulum laoreet, massa sed congue bibendum, lacus massa mattis arcu, quis pellentesque erat sapien et lacus. Phasellus vitae est convallis, molestie elit ac, volutpat sem. Morbi vitae nibh risus. Etiam dignissim, mauris quis consequat vehicula, nisi ex varius tellus, sit amet efficitur nisi tortor et lorem. Pellentesque elementum lectus vel magna auctor, at vehicula nulla feugiat. Phasellus a nulla rhoncus, mollis est et, suscipit nunc. Proin pulvinar turpis accumsan, rutrum diam in, vulputate lectus. Integer blandit dignissim orci, a consequat nibh cursus eget. Mauris convallis dignissim lacus in tincidunt. Phasellus blandit nisl et porttitor ornare. Nam quis justo orci.
Integer sodales dolor ut purus rhoncus egestas. Integer at pharetra mi. Mauris nec nibh quis turpis posuere commodo et a ante. Integer aliquet leo ipsum, non tempus lacus varius vitae. Vestibulum volutpat et leo ac posuere. Proin vel tortor nec purus consequat sollicitudin. Vestibulum finibus, justo bibendum bibendum pretium, lectus ligula feugiat massa, a ultricies felis nibh eu libero. Aliquam tincidunt sit amet leo ut efficitur. Fusce libero lectus, semper eu erat sit amet, consectetur pellentesque leo. Mauris vel volutpat augue. Quisque commodo mi sit amet libero cursus vulputate.
Aenean semper ligula sem. Morbi varius dictum sollicitudin. Praesent nec mi sit amet tortor vulputate hendrerit et in felis. Nam ut magna sem. Sed varius mauris vitae diam feugiat rhoncus. In imperdiet laoreet ipsum sit amet rutrum. Integer est metus, aliquam nec mauris luctus, convallis facilisis nunc. Proin pharetra libero nec lacinia ornare. Curabitur sed sodales quam, vitae viverra elit. Cras luctus egestas libero, non fermentum ex dictum vitae. In vitae nisl non neque vehicula pharetra eget id neque.
Sed est mauris, vulputate sed iaculis sit amet, tincidunt vitae ipsum. Nunc non tellus sed sem venenatis vestibulum. Praesent pharetra volutpat consectetur. Donec ut arcu quis leo consectetur ullamcorper. Duis efficitur lectus quam, id condimentum nisi molestie non. Mauris sit amet orci commodo, tempor arcu nec, egestas sapien. Sed tellus nunc, placerat eu lectus eget, malesuada sagittis mi. Sed porta a urna auctor rutrum. Morbi quis facilisis arcu, id sodales turpis. Duis semper suscipit dui. Suspendisse vitae elit non elit iaculis venenatis quis a lacus. Phasellus efficitur porta velit vitae bibendum.
Fusce lacinia interdum metus eget posuere. In volutpat porta malesuada. Vivamus ac imperdiet velit, sit amet cursus felis. Vestibulum condimentum tempus viverra. Vestibulum iaculis rhoncus tortor. Ut molestie massa lacus. Donec auctor felis nibh, ac fermentum sapien venenatis quis. In orci odio, tempor id viverra et, mollis sed lectus. Nunc aliquet turpis vel lorem vulputate, non fringilla lacus vehicula.
Vivamus egestas est a urna vulputate tempus. Donec dui dolor, laoreet sed nulla et, faucibus molestie leo. Aliquam laoreet ligula quam, eget ultrices ex aliquam id. Duis pretium libero lorem, at suscipit felis interdum vel. Ut elementum suscipit arcu. Integer quis lectus at mauris consequat maximus. Cras non magna congue, commodo neque a, tincidunt turpis. Morbi ex massa, eleifend dapibus porta vitae, aliquam id neque. Duis ac finibus justo.
Nunc eu semper neque. Morbi vehicula vulputate augue eu venenatis. Fusce dapibus ornare ex, a pulvinar magna consectetur sit amet. Phasellus consectetur quam non arcu dictum ultricies. Morbi lacus sem, ultricies vel tincidunt vitae, fermentum et mi. Vivamus quis mauris dolor. Vestibulum libero orci, faucibus convallis nulla et, interdum mattis leo. Morbi sapien urna, lobortis sed dignissim in, egestas eget augue. Morbi pellentesque commodo nunc a egestas. Duis molestie, nulla ut molestie maximus, sapien urna auctor lectus, nec eleifend dolor sem non orci.
Integer id luctus nisi. Ut non volutpat urna, id pretium enim. Proin pretium orci eu urna tristique, ac pretium enim auctor. Integer auctor aliquet pellentesque. Morbi sit amet rhoncus enim, vel ornare tortor. Donec bibendum diam at posuere volutpat. Nullam aliquam dolor vel eros rutrum ultrices. Proin vitae fringilla velit. Aliquam erat volutpat. Suspendisse potenti. Vivamus consequat tellus eget massa tempor volutpat. Sed sagittis tellus in fermentum vulputate. Etiam porta nec eros eu consequat. Aliquam erat volutpat. Vestibulum euismod accumsan libero, et auctor odio. Maecenas feugiat odio eget cursus consequat.
Sed pellentesque erat dui. Donec malesuada pharetra tortor eu placerat. Mauris eget vestibulum est. Nulla suscipit varius urna eget efficitur. Suspendisse at eros et eros mattis eleifend. Suspendisse vel libero id ex efficitur gravida. Vestibulum non dictum augue. Aliquam a dui in arcu varius hendrerit. Duis lobortis vehicula massa, ac consequat eros sollicitudin id. Vivamus tristique sem ac dictum finibus. Cras eleifend dignissim purus at facilisis. Sed cursus malesuada ipsum, quis tempus nisi malesuada in. Nunc hendrerit vulputate diam, sit amet sollicitudin est sagittis non. Donec a faucibus neque, eget gravida ipsum.
Aenean viverra dignissim arcu, in suscipit neque vulputate id. Nulla elementum, magna quis tincidunt posuere, lacus metus auctor mauris, et condimentum libero tortor non lectus. Aliquam iaculis sem in libero auctor, nec vulputate lacus gravida. Fusce porta, lacus a fermentum blandit, est lacus iaculis metus, nec hendrerit ipsum sem vitae lectus. Aenean auctor, elit eu gravida convallis, risus tellus sodales augue, in condimentum mauris nibh non elit. In vitae commodo tortor. Maecenas eu blandit eros. Proin lobortis nulla at turpis tristique vestibulum. Curabitur faucibus scelerisque ante eget ultricies. Mauris egestas porttitor facilisis. Vivamus vitae tortor tortor. Sed placerat gravida velit, id rhoncus tellus. Mauris sed cursus eros. Curabitur elementum odio a enim mattis, eget convallis augue eleifend. Vivamus a purus at nulla blandit viverra eget nec velit.
Nam commodo quam non mi feugiat malesuada eget vitae lorem. Nunc fermentum quam ac quam mollis bibendum. Praesent lobortis leo in urna sodales, ut hendrerit leo varius. Praesent vel turpis vitae odio laoreet accumsan. Aenean consectetur sollicitudin eros, vitae iaculis mi sollicitudin sit amet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed suscipit ligula. Morbi eu est porta, iaculis turpis ac, molestie enim. Nulla metus metus, vehicula a pretium semper, fermentum et diam. Praesent luctus diam ut cursus faucibus. Proin congue aliquet nisl, sit amet eleifend purus auctor eget. Ut tortor tellus, sollicitudin et odio ut, aliquam volutpat elit.
Vivamus ac odio nec purus dictum sagittis. Quisque ultricies ut ex ut congue. Mauris vitae ipsum ipsum. Mauris vulputate ullamcorper consequat. Aliquam rhoncus eu elit at venenatis. Mauris auctor mauris odio, interdum luctus dui posuere sit amet. Mauris purus odio, porttitor a tempor molestie, accumsan sed tortor. In augue lectus, venenatis a lacinia sit amet, facilisis vel diam.
Donec lacinia sit amet felis in venenatis. Sed et augue et ex commodo consectetur vel ut massa. Maecenas pellentesque blandit fringilla. Cras eu aliquet urna. Aenean consequat nunc eget mi elementum efficitur. Fusce eros est, sollicitudin ut pharetra sit amet, hendrerit non nisl. Aenean mattis magna sed faucibus maximus. Nunc aliquet tellus eget metus ultricies sodales. Donec ac risus quis nisi ultrices suscipit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ultrices urna ut erat consectetur, sit amet pretium libero vulputate.
Nulla interdum posuere consectetur. Donec tincidunt risus ac ante fermentum luctus. Nam lobortis velit sit amet enim tristique dapibus. Quisque tincidunt nibh diam, a vulputate tortor varius eu. Nullam et erat justo. Morbi eget molestie eros, vitae imperdiet neque. Praesent eleifend urna nisi, vel mattis ligula consectetur vitae. Sed sit amet congue erat. Sed sit amet odio ut nisl imperdiet finibus ut in augue. Sed pulvinar sem eget arcu mollis, nec mattis mi luctus. Phasellus tempus augue at consequat viverra. Nunc sit amet congue mi. Sed augue tortor, facilisis sit amet ultricies non, tincidunt at nisl. Curabitur suscipit magna eget volutpat venenatis. Curabitur sed dictum eros. Etiam pretium nibh vel fringilla consequat.
Sed suscipit libero ut erat ornare sollicitudin. Nulla rhoncus mollis pretium. Mauris consectetur bibendum viverra. Nullam vulputate ipsum vitae ipsum ornare posuere. Duis aliquam pellentesque erat dignissim posuere. In tempus tincidunt dui sit amet mollis. Curabitur ut aliquet ex. Nam interdum, massa at feugiat fringilla, leo ligula viverra erat, vitae rhoncus mi tellus sit amet massa. Quisque ultricies augue accumsan, sollicitudin sem vitae, scelerisque diam. Cras tincidunt, elit quis rhoncus condimentum, ex massa placerat neque, eu commodo leo dui sit amet lacus. Maecenas ullamcorper et elit nec blandit. Vivamus non tellus dignissim, molestie ligula vel, fringilla nunc. Suspendisse porttitor ullamcorper leo quis dictum. Donec ullamcorper nibh in lacus pellentesque lacinia. Duis ut mattis justo.
Vestibulum sodales ligula lacinia ultrices tempus. Aenean elementum felis ligula, eget consequat tellus facilisis in. Nam fermentum, nunc a vehicula ultrices, erat odio ultricies metus, nec varius lorem mauris et neque. Donec molestie ultricies ornare. In fringilla turpis massa. Nulla vel magna nec nibh vehicula lacinia quis eget enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum quis magna ultricies, lacinia eros et, scelerisque leo. Integer scelerisque libero tempus elit lacinia, quis interdum velit lacinia. Vivamus aliquet, tellus sed convallis sollicitudin, orci ex dictum quam, eget gravida metus purus eget eros. Cras venenatis sapien sit amet finibus dictum. Donec aliquam lectus pretium massa fringilla laoreet. Maecenas sed sodales massa, finibus eleifend nisl.
In et mattis ex. Fusce accumsan lacus ac urna sollicitudin posuere. In non libero vitae neque posuere commodo ac sit amet neque. Ut maximus est et odio scelerisque, et congue quam ultrices. Curabitur cursus eget turpis sed bibendum. Praesent vel felis at erat fringilla volutpat vitae sed mi. Pellentesque ac diam nulla.
In sit amet purus quis leo suscipit hendrerit. Aenean diam ante, vestibulum vitae maximus sit amet, imperdiet et ipsum. Duis porta cursus ligula, nec ultricies nibh mattis quis. Aliquam semper malesuada neque. Maecenas at dolor vulputate, venenatis mi vel, consequat neque. Donec nec nisi scelerisque, feugiat ipsum porta, pretium massa. Donec mattis felis vitae nulla imperdiet fermentum in vulputate massa. Aenean ornare gravida fringilla. Vivamus lacinia massa et ligula vulputate, vel interdum sem consequat. Etiam tortor turpis, auctor at augue id, pellentesque tempor risus.
Donec vitae porta odio. Ut ullamcorper elit tempor vestibulum hendrerit. Etiam aliquam, lorem maximus sagittis ultrices, nibh purus gravida enim, eu convallis dui purus quis nisl. Nullam at faucibus velit, non pellentesque eros. Curabitur ut erat ac nulla fringilla eleifend. Maecenas laoreet nibh vel elementum efficitur. Sed at nibh ut dolor vulputate consectetur ut non ligula. Vestibulum dui nunc, pretium et risus nec, finibus porta arcu. Pellentesque sodales urna et commodo faucibus. Morbi ultrices faucibus rutrum. Proin scelerisque tortor ac lacus molestie, quis aliquam lorem efficitur. Proin enim erat, porttitor a purus malesuada, volutpat congue ante. Maecenas congue enim eget nisl vehicula, sed luctus lectus rutrum. Duis accumsan turpis vel nunc rhoncus, id finibus ex porta. Quisque sit amet est non leo consequat laoreet eu non ipsum. Duis metus risus, dictum et est a, convallis tempor neque.
Fusce fermentum mauris eu mauris posuere consectetur. Morbi porttitor nulla bibendum eros pellentesque condimentum. Aenean vitae mattis ante. Duis ultricies pharetra dolor, in lacinia augue vulputate non. Suspendisse elit risus, aliquam et tincidunt sit amet, fringilla sed orci. Morbi in egestas nunc. Vivamus sit amet quam ullamcorper eros commodo facilisis nec sed risus. Phasellus lobortis erat ac metus pharetra, id porta est auctor. Morbi pellentesque sodales arcu pulvinar aliquam. Donec blandit non ligula ac pharetra. Nullam nec est ligula. Cras sed volutpat erat, ac feugiat odio. Curabitur dapibus, ipsum id tempor volutpat, turpis tortor tempor tellus, id dignissim felis felis quis turpis.
Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce ornare eget purus non pretium. Etiam at neque in lectus sodales condimentum at id arcu. Cras non dapibus magna. Pellentesque eu pulvinar urna. Pellentesque nunc est, interdum et ex non, pretium tempor erat. Phasellus vitae quam vel turpis lobortis mollis vitae a ligula. Aenean sed iaculis mauris.
Nullam ut libero eget purus placerat tempus in posuere nunc. Aliquam tempus egestas pretium. Etiam lacinia orci justo, sit amet tincidunt mauris molestie vel. In tincidunt nulla nec odio venenatis scelerisque. Morbi dapibus dui in nulla venenatis gravida eget at mi. Integer laoreet ex eu nisl condimentum, vel molestie ipsum ornare. Mauris vitae aliquam justo. Duis eget tristique dui. Integer nec justo massa. Proin placerat dapibus nisi. Curabitur aliquam vel lacus sit amet viverra. Praesent iaculis pellentesque tempor. Maecenas porta pharetra metus nec hendrerit.
Aenean elementum quis libero non scelerisque. Mauris tristique nunc est, id interdum turpis luctus non. Donec erat enim, semper eget diam pellentesque, viverra ultricies mi. Etiam non eros nec ipsum accumsan facilisis. Integer ultrices libero at consequat scelerisque. Ut bibendum massa nec nunc tempor blandit. Aenean felis dolor, semper ut purus sit amet, iaculis blandit diam. Nunc sed dui sapien. Mauris posuere, ante id sodales placerat, tellus magna porta velit, tincidunt scelerisque erat felis nec felis. In hac habitasse platea dictumst. Pellentesque ipsum ante, ultricies eget porttitor ac, elementum in risus. Suspendisse et elit eu orci fringilla laoreet. Aliquam at sollicitudin magna.
Duis lorem turpis, semper quis ultrices ullamcorper, placerat in sapien. Ut tristique eleifend volutpat. Nullam ut elit tincidunt, tempor lacus sed, molestie metus. Donec sed commodo risus. Cras suscipit ac est eget tempus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam sapien diam, ornare nec luctus et, venenatis nec turpis. Nam id dui at diam fermentum cursus. Cras nec neque a diam tristique molestie. Maecenas id ipsum quis tellus laoreet egestas nec facilisis lorem. Proin bibendum ullamcorper vestibulum.
Aliquam erat volutpat. Aliquam tempus auctor mauris in ullamcorper. Morbi a nisl non lacus efficitur lacinia. Ut sollicitudin magna tincidunt erat vulputate egestas. Donec tempor gravida enim. Nam libero leo, pretium vitae dolor eu, congue pellentesque mauris. Pellentesque scelerisque nec ex et pellentesque. Sed sed rutrum mauris, id scelerisque nisi.
Maecenas accumsan lorem et lacus congue auctor. Quisque egestas iaculis purus a pulvinar. Mauris interdum vitae odio vel ultricies. Quisque dictum ornare vestibulum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vestibulum quis commodo nunc, in maximus justo. Pellentesque a ipsum libero.
Pellentesque leo neque, mattis eget aliquet at, posuere ac quam. Fusce vitae felis sed purus tempor placerat. Mauris vel erat eget justo tincidunt tincidunt sed sit amet ipsum. Integer gravida tellus sit amet maximus vestibulum. Quisque et metus aliquet, semper enim pharetra, dapibus erat. Morbi cursus vehicula nisl et mollis. Suspendisse feugiat hendrerit interdum. Morbi erat tortor, interdum dapibus dui eget, dapibus tristique mi. Nulla eu dolor laoreet, congue dui eleifend, vehicula diam. Pellentesque eget est nec lectus ullamcorper accumsan nec at ex. Nam fermentum, metus ut euismod egestas, urna ex ultrices ante, ut posuere risus odio at sem. Mauris ut scelerisque nunc. Suspendisse ac tempus tellus. In tincidunt aliquam ligula, a vestibulum quam feugiat sit amet. Donec cursus velit sit amet dolor ultrices tempor.
Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi sed ex interdum, dictum odio ut, gravida ligula. Nunc in condimentum mauris, a sollicitudin est. Sed imperdiet porta odio, ut lobortis sapien varius ut. Duis euismod tempor finibus. In hac habitasse platea dictumst. Proin aliquet vehicula finibus. Donec lacinia mi ex, a mattis nisl pretium quis.
In viverra elit in tempor convallis. Suspendisse potenti. Nulla nec gravida tortor, quis finibus nibh. Maecenas nec maximus metus. Nunc sagittis consectetur odio, at eleifend mi varius commodo. Vestibulum scelerisque nulla faucibus tortor finibus mollis. Ut metus elit, convallis at venenatis sed, rutrum in ipsum.
Phasellus posuere feugiat nisl, ut sagittis lectus rhoncus ut. Vivamus vitae ipsum nibh. Etiam id consequat quam. Curabitur fringilla, ex aliquet pretium iaculis, arcu velit dapibus arcu, eu euismod mauris lectus sit amet massa. Curabitur nisl purus, rutrum blandit maximus vitae, consectetur ut diam. Quisque auctor tincidunt lacus, ut scelerisque nunc sodales sit amet. Morbi blandit vestibulum tellus a elementum. Integer porttitor nisi at nisi molestie mattis. Duis ultrices eget ante ac suscipit. Maecenas quis purus id eros imperdiet scelerisque. Nunc vestibulum, arcu hendrerit feugiat ornare, felis turpis congue augue, eu vulputate massa neque sed est. Proin sit amet eleifend mauris, sit amet iaculis justo.
Vestibulum ut massa ullamcorper ipsum molestie sagittis. Vestibulum vulputate convallis libero, et tempus sapien facilisis vitae. Sed blandit, justo sed suscipit aliquam, diam lacus tincidunt est, vitae viverra felis turpis consectetur dolor. Quisque eget sem eget justo suscipit aliquam quis non odio. Vivamus tristique eleifend velit, eu fringilla ante fringilla vel. In id porta arcu, eget vehicula lorem. Vestibulum rutrum nulla lectus, molestie laoreet libero ornare id. Nunc pulvinar molestie nunc sit amet euismod. Sed eleifend augue feugiat, convallis ligula non, ullamcorper eros. Vestibulum lobortis congue iaculis. Morbi sit amet rutrum ipsum, a accumsan sem. Sed efficitur fermentum nunc, nec volutpat sem feugiat vel.
Curabitur quis ex augue. Pellentesque pharetra sed arcu in sollicitudin. In nec vulputate felis. Suspendisse consequat sit amet velit sodales cursus. Sed cursus at nulla sit amet tincidunt. In elementum, turpis nec scelerisque varius, nisl ante hendrerit ligula, eu scelerisque lorem erat eu arcu. Proin magna lorem, aliquet eu ligula id, blandit posuere ligula. Ut congue lacinia orci.
Mauris est erat, auctor eu scelerisque quis, rutrum eget sapien. Quisque consectetur volutpat leo in molestie. Maecenas tincidunt ligula vel mi feugiat maximus. Fusce egestas turpis non quam blandit vestibulum. Sed vel convallis ante. Nulla dapibus tincidunt leo nec tincidunt. Aliquam efficitur leo sit amet massa blandit feugiat. Duis venenatis nisi sit amet magna tincidunt, in auctor sem maximus. Curabitur quis metus non velit efficitur condimentum eget id arcu. Aliquam eleifend purus arcu, ac lobortis purus aliquam sit amet. Etiam et condimentum nunc. Praesent quis nisi at libero viverra eleifend vitae at nisl. Nulla euismod libero ac lorem varius varius.
Donec lobortis rutrum felis, id congue eros hendrerit id. Phasellus elementum elit vel tortor ornare, non scelerisque sapien consequat. Pellentesque sem ex, mattis vitae enim ut, placerat dignissim enim. Nulla convallis eget lorem nec varius. In id placerat justo, a eleifend nibh. Curabitur turpis risus, rhoncus mattis turpis vitae, posuere tincidunt enim. Aliquam volutpat erat mi, ac fermentum magna suscipit quis. Cras ac aliquet nibh.
Aliquam rhoncus fermentum commodo. Aliquam orci turpis, auctor vitae malesuada in, pretium quis libero. Nulla commodo condimentum erat, quis euismod augue imperdiet vitae. Donec luctus eros quis quam consectetur posuere. Nunc ullamcorper eu lectus et semper. Donec vehicula tempus dapibus. Duis auctor tempor ornare. Maecenas ut tellus nisl. Etiam condimentum turpis non metus molestie, eget ullamcorper lectus interdum. Donec quis diam in justo egestas rhoncus vel ac neque. Praesent hendrerit ullamcorper purus ut suscipit. Sed non tincidunt tortor.
Proin a quam ut lacus faucibus vulputate. Aliquam odio nunc, convallis et consectetur a, pharetra ut nulla. Pellentesque sed urna sit amet ipsum aliquet mollis. Maecenas a tincidunt ex. Sed sodales dolor a odio sodales, eget congue sem eleifend. Vivamus aliquet eleifend arcu ac finibus. Suspendisse non tortor urna. Nam quis consequat nisl. Nullam quis tincidunt velit, vel aliquet sem. Pellentesque consequat nisl ut orci dignissim, non convallis lectus sodales. Proin vitae vestibulum est. Quisque metus diam, elementum at ultricies eu, dictum in nisi. Nam ullamcorper nec urna eget congue. Aliquam ultrices congue porttitor. Vivamus at felis sit amet dolor volutpat luctus.
Etiam eu mi vel metus porttitor suscipit. Etiam lacinia libero et condimentum imperdiet. Phasellus rutrum congue velit at scelerisque. Proin sed placerat risus. Integer nec justo vitae odio hendrerit tristique quis vitae velit. Quisque sed volutpat nulla, sit amet sagittis leo. Aenean vel interdum nibh. Nullam non pharetra urna. Donec quam orci, tempus et mattis at, pulvinar in libero. Fusce ullamcorper tristique vestibulum. Duis condimentum sed lorem eu convallis. Duis et purus facilisis, laoreet sem ac, malesuada diam. Maecenas ultrices bibendum congue.
Proin nibh elit, pulvinar et eleifend in, ultrices luctus nisl. Vivamus vestibulum placerat urna, in dictum arcu auctor vitae. Mauris massa tortor, imperdiet vitae odio eu, mattis suscipit ex. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur pellentesque magna eu mollis tempus. Fusce fringilla odio erat, vel porta libero rhoncus non. Praesent et ipsum non lorem tristique rhoncus at non ex. Proin eros purus, lacinia sed vehicula egestas, suscipit sit amet metus. Aenean ac felis hendrerit velit imperdiet porttitor.
Morbi consectetur, elit ac faucibus maximus, enim lacus lobortis augue, quis viverra purus massa laoreet urna. Nulla feugiat hendrerit lorem ac bibendum. Donec a porttitor lectus, sit amet commodo ante. Nunc tristique lectus quis elit laoreet, in molestie est egestas. Duis pretium euismod elementum. Ut ut enim at orci ultricies viverra id quis ligula. Maecenas tempus porttitor fringilla.
Sed eleifend libero viverra, mattis libero fringilla, blandit dolor. Nullam at est rutrum, rhoncus nisl non, aliquet enim. Fusce sed sem augue. Sed vestibulum arcu nibh, quis pellentesque lectus molestie sed. Morbi blandit neque sit amet massa ultricies hendrerit. Cras quis scelerisque libero. Aenean dictum ante non metus lacinia blandit. Nulla commodo ex id purus egestas, a sollicitudin nibh tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum tempus arcu ut nisl eleifend efficitur. Morbi iaculis vel eros eget convallis. Phasellus finibus, neque a iaculis congue, nunc dolor tempor metus, ut laoreet leo libero vitae augue. Nulla ac tempor libero, nec viverra lacus. Cras quis rutrum nisi. Cras risus metus, elementum in orci et, vehicula vulputate neque.
Vivamus ipsum leo, vulputate vel est vitae, feugiat sodales sem. Curabitur malesuada dictum tristique. Fusce elementum sagittis nunc eu lacinia. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam vitae nisl auctor, iaculis odio non, viverra orci. Fusce iaculis odio non ex tincidunt, ac dictum ipsum cursus. Aenean condimentum pharetra ultrices. Praesent in erat quis leo lobortis tincidunt quis posuere augue. Ut porta mauris lacus, quis porta sem ultricies et. Aenean a semper eros. Etiam ac sapien in orci ultrices molestie vitae ut nunc. Maecenas facilisis felis sit amet neque finibus, in sagittis dolor facilisis. Nunc vehicula porttitor posuere. Pellentesque feugiat ante magna. Aliquam vitae sem est.
Sed et libero nec elit tincidunt pretium. Suspendisse nec volutpat dolor. Phasellus scelerisque nunc neque, sit amet posuere est fringilla quis. Maecenas sed nulla ac tortor rutrum pulvinar. Morbi ut sapien urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris tristique neque eget libero bibendum iaculis. Cras finibus urna et tellus sollicitudin, aliquet tincidunt orci vestibulum. In hac habitasse platea dictumst. Vestibulum posuere felis a sollicitudin interdum. Fusce pulvinar, ante ut ullamcorper cursus, libero massa pulvinar sem, at convallis leo sem eget diam. Aliquam vestibulum erat a blandit interdum. Donec a tortor arcu. Duis viverra velit sit amet nunc pharetra interdum.
Pellentesque eget dolor sit amet neque consectetur lobortis. Morbi sed molestie lacus. Sed convallis luctus bibendum. Suspendisse sed ante eget justo maximus iaculis tempus et enim. Nam ut commodo libero. Suspendisse potenti. Vestibulum vulputate porttitor nisl, non lacinia justo. Nam luctus, elit ut interdum iaculis, mi ante feugiat magna, in eleifend augue massa et lectus. Nulla facilisi. Praesent eros sapien, luctus id ultricies et, tincidunt quis massa. Donec dignissim elit vel nisi facilisis, vel aliquam ligula tristique. Vestibulum vestibulum vestibulum urna. Sed posuere dignissim fringilla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
In lacinia, nunc ac fringilla tempus, libero velit feugiat eros, ut iaculis mauris ipsum eget turpis. Etiam tristique libero tortor, in hendrerit velit ultricies eget. Sed commodo sapien eu nunc finibus, sagittis tempus justo semper. Praesent facilisis nulla ut nisi interdum, id ultricies est volutpat. Praesent pharetra enim eget turpis elementum pulvinar. Maecenas nibh diam, euismod non gravida nec, aliquam sed tellus. Proin ullamcorper ex faucibus, elementum neque vel, egestas augue. Morbi aliquet sem vitae pretium tempus. Etiam sagittis sagittis erat et ullamcorper. Nulla risus lorem, sodales sit amet aliquam et, ultricies eu ipsum. Proin gravida non risus et mattis. Donec tristique quis ligula sed rhoncus. Fusce vestibulum, magna in luctus luctus, felis nunc porta est, eu iaculis leo ante quis leo.
Aliquam viverra id ipsum in semper. Curabitur nunc neque, ultrices quis vestibulum at, semper eget tellus. Donec quis ultrices orci. Donec pulvinar tortor a dolor dictum, ultricies accumsan neque consequat. Maecenas non pellentesque urna, ac egestas turpis. Sed sodales porta metus. Sed tincidunt pretium velit nec maximus. Vivamus efficitur feugiat est, ac luctus mi interdum suscipit. Nam id nulla et risus pretium fermentum. Duis at commodo est.
Mauris id purus orci. Praesent fringilla fermentum congue. Praesent eget quam in nisl ultrices porta ac in est. Suspendisse ut posuere sapien. Suspendisse aliquet tellus lacinia urna efficitur, sed fringilla nisi rhoncus. Morbi at volutpat massa. Donec venenatis posuere lorem a accumsan. In iaculis ligula vel enim pharetra semper. Quisque a nunc et magna elementum fermentum nec in erat. Nam pharetra magna auctor dapibus volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin in nibh ut mauris tincidunt interdum. Sed dictum pellentesque eleifend. Nullam in consequat lorem, eget luctus ex.
Aenean pellentesque nisl ligula, et fringilla nisl luctus at. Sed hendrerit consequat nunc, vitae sollicitudin ex faucibus ut. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis ut est sed dui luctus convallis eget quis risus. Quisque sollicitudin nulla vitae tortor accumsan, a ullamcorper neque bibendum. Aenean lobortis, orci ut consequat faucibus, justo lorem vestibulum arcu, sit amet facilisis nisl mi sit amet metus. Aliquam commodo purus orci, at varius tortor facilisis sit amet. Fusce interdum mauris elit, eu viverra felis tempus at. Vivamus sit amet neque id nisl posuere pulvinar. Proin vel velit sit amet neque tristique eleifend. Quisque malesuada, enim nec molestie tristique, urna augue imperdiet eros, ut dignissim tellus nunc non lectus. Nullam porttitor vel tellus eu imperdiet.
Phasellus mattis, magna id hendrerit aliquam, enim nunc egestas eros, at sollicitudin odio nulla sed nisi. Maecenas viverra purus a turpis hendrerit hendrerit. Maecenas quis tristique nulla. Etiam in dui et diam vestibulum iaculis. Phasellus mauris est, tristique eu pulvinar at, pharetra sit amet neque. Pellentesque cursus magna ex, sed ullamcorper velit consequat at. Cras vulputate odio lacinia sapien molestie fringilla. Nunc pharetra pulvinar diam nec pellentesque. Mauris dictum bibendum mauris, sed aliquet sapien egestas nec. Fusce ultricies, ex ultrices convallis rutrum, purus nibh elementum turpis, nec ultricies dui nisl suscipit odio. Pellentesque ligula nisl, convallis consequat faucibus ac, condimentum ut odio. Fusce eu diam efficitur, porttitor arcu vel, auctor tellus. Nunc malesuada sem eu sem iaculis, eu viverra risus consequat. In massa neque, vulputate sit amet nisl consequat, interdum convallis odio. Quisque elementum id lorem sed vehicula. Quisque at ante nisi.
Suspendisse aliquet, felis vitae auctor rutrum, justo lectus elementum odio, non varius massa purus ac nisi. Vestibulum eu erat libero. Pellentesque cursus mauris mauris, sed rutrum enim fermentum nec. Donec id libero felis. Proin facilisis, magna et consequat imperdiet, neque magna lobortis lectus, at feugiat leo enim ut nibh. Curabitur cursus aliquet condimentum. Mauris eros nisi, egestas placerat elit sed, tincidunt faucibus leo. Mauris quis efficitur lectus, ac pharetra neque.
Duis auctor iaculis varius. Fusce efficitur condimentum mauris, vitae pulvinar purus pharetra in. Duis consectetur leo sed luctus varius. Maecenas quis tortor ut mi varius luctus non id diam. Mauris vestibulum velit at rutrum tincidunt. Sed ut facilisis nulla, euismod pretium nunc. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce scelerisque nibh non magna lacinia, sed pulvinar arcu mattis. Morbi semper turpis quis aliquet fringilla. In nec suscipit turpis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam vehicula, leo vel euismod bibendum, risus magna tincidunt lacus, in ornare tellus nisi vitae risus. Praesent viverra dictum ipsum, in faucibus nisl tempor quis.
Phasellus imperdiet nisl dui, sit amet efficitur erat suscipit et. In porta libero ac eros ullamcorper, in viverra lorem maximus. Vivamus ut ullamcorper augue, id interdum justo. Nam ut semper lorem. Praesent vitae tristique odio. Nunc vitae dignissim enim, sed finibus nunc. Mauris a purus efficitur, suscipit nisl eleifend, feugiat massa. Suspendisse ultrices commodo pretium. Aliquam viverra ante nulla, sed rutrum metus vestibulum ac. Maecenas accumsan purus ultrices congue tempus.
Aliquam vitae nisl sed diam ornare faucibus ac vitae ipsum. Pellentesque eget augue vitae mi vehicula vulputate ut ullamcorper sem. Phasellus feugiat volutpat eros quis facilisis. Duis auctor tincidunt felis et feugiat. Nullam et viverra eros, non scelerisque lacus. Sed consectetur vestibulum augue quis dignissim. Fusce ut augue volutpat, bibendum dolor at, iaculis quam. Etiam finibus elit et tellus ultrices, ut fringilla urna mattis. Duis vel massa ut lacus blandit ultrices sit amet ut arcu. Etiam nunc neque, imperdiet nec magna non, mollis tristique massa. Nunc lorem dui, dictum nec sagittis a, mollis eget quam. Ut in orci erat. Sed rhoncus odio at turpis viverra auctor. Aenean feugiat vehicula lectus. Etiam posuere leo non tortor lacinia ornare.
Aenean eu euismod neque, vitae eleifend purus. Aliquam pulvinar eleifend ipsum vitae tempor. Ut ullamcorper nisl sed ligula tempor, eu molestie arcu sollicitudin. Donec sagittis bibendum eros vitae ornare. Aenean consectetur ex ut neque imperdiet viverra vitae sed est. Nullam aliquam sed metus sed tincidunt. Praesent lacinia interdum nulla, vitae eleifend purus tincidunt non. Aenean ac nulla id ex facilisis tincidunt. Nunc nec luctus dolor. Aliquam erat volutpat. Mauris ac ultrices nulla. Ut sed purus quis orci malesuada sagittis.
Integer eget enim a quam efficitur maximus. In fermentum, diam in vulputate ornare, nisi massa dapibus massa, ut tincidunt mauris est vel ligula. In commodo eget libero ac interdum. Curabitur justo nunc, mollis et libero ut, interdum aliquam leo. Maecenas porttitor pulvinar lacinia. Suspendisse vitae sapien eu massa tincidunt faucibus. Ut placerat pellentesque maximus. Nullam venenatis libero id condimentum finibus. Quisque sem nibh, dictum eu sem vitae, vehicula molestie enim. Nullam libero tellus, molestie sit amet nisl ut, blandit tincidunt mauris. Cras lobortis, quam vel sollicitudin bibendum, risus elit porta arcu, et condimentum elit metus quis nisi.
Donec pellentesque tristique rutrum. Morbi lobortis iaculis ligula, vel convallis odio varius eget. Praesent dictum metus finibus odio dignissim, ac eleifend est ullamcorper. Donec in nisi tempus, efficitur risus vel, pulvinar mauris. In hac habitasse platea dictumst. Suspendisse fringilla leo sem, eu feugiat lorem malesuada at. Donec lacinia vulputate metus ac laoreet. Cras tortor nulla, euismod quis congue in, facilisis nec diam. Vivamus dictum lorem vel metus tincidunt vestibulum.
Maecenas iaculis quis erat et lacinia. Cras libero libero, fermentum vitae varius eu, eleifend cursus nisi. Cras finibus lorem lectus, at ullamcorper felis iaculis eu. Donec placerat augue eget libero semper consequat. Nunc sed lacus ullamcorper, sollicitudin odio eget, ultrices sem. Donec congue sodales consectetur. Sed eros tellus, imperdiet non pretium ultricies, pulvinar quis massa. Fusce pulvinar, ante eget dapibus lobortis, libero mi tincidunt risus, sed sagittis lectus nisl eget felis. Maecenas suscipit facilisis sem ut tempor. Vivamus at sapien lacus.
Morbi a blandit dolor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi venenatis justo eget urna vehicula, suscipit auctor turpis pharetra. Suspendisse a condimentum ex. Cras volutpat faucibus urna non malesuada. Donec commodo, urna sit amet consequat dictum, nunc magna finibus arcu, non semper urna diam vel massa. Maecenas ut est lacus. Pellentesque iaculis dictum est, quis dignissim magna pharetra vitae.
Quisque vitae ex sit amet erat fermentum consectetur ut at ligula. Suspendisse ultricies mollis convallis. Cras et fringilla ex. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean et est dictum, eleifend diam ut, aliquam augue. Sed faucibus at odio a pellentesque. Nam ultrices, risus at consectetur pretium, augue mi molestie est, at laoreet mauris justo quis odio.
Vestibulum et nisl varius, volutpat dolor ac, interdum est. Morbi vel magna erat. Suspendisse consectetur sagittis finibus. Sed vulputate arcu a nisi euismod, sit amet tempor erat vulputate. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer mi sapien, lacinia ac tincidunt at, malesuada nec massa. Nunc lacinia lacus id nisl gravida, vel dictum nunc molestie. Vivamus viverra, orci ac viverra sagittis, lacus tellus bibendum est, vel consectetur elit mauris quis nulla. Praesent tempus dolor at sem porttitor bibendum.
Sed lacinia porttitor eros, vitae consectetur dui laoreet rhoncus. Suspendisse arcu erat, semper eu maximus in, finibus viverra nisi. Fusce vehicula magna quis est vehicula, quis convallis diam tempus. Curabitur et dapibus neque. Vestibulum blandit libero ut odio mattis mattis. Sed non nisi vestibulum, malesuada libero sit amet, imperdiet quam. Nunc maximus, lacus eu bibendum placerat, mi mauris congue arcu, eget consectetur urna felis quis elit. Vestibulum fermentum dignissim diam, et iaculis ligula interdum vel. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse ac finibus eros, posuere rutrum leo.
Aenean tincidunt nulla et sapien viverra imperdiet feugiat vitae eros. Fusce ultrices elementum nisi, a congue purus pulvinar vel. Maecenas eu sagittis sem. Fusce molestie sollicitudin libero, a vestibulum metus tincidunt sit amet. Aliquam tristique lorem sed tortor feugiat, non dignissim mauris aliquet. Etiam dictum quam efficitur leo sagittis interdum. Ut lacus arcu, congue sed magna vitae, feugiat consectetur dui. Aenean nisi leo, varius sollicitudin imperdiet quis, molestie a odio.
Fusce in libero vitae libero interdum facilisis eget et nulla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi varius dui ac risus varius convallis. Ut turpis arcu, feugiat et leo vitae, consectetur vulputate nibh. Duis feugiat metus sit amet felis bibendum, et pharetra ligula viverra. Suspendisse condimentum eros risus, ut luctus nulla pulvinar vitae. Vestibulum id fermentum urna. Nulla dolor neque, aliquam eget arcu vitae, venenatis hendrerit tellus. Praesent sit amet accumsan mi.
Phasellus in ex cursus, congue diam eu, laoreet augue. Sed semper tellus quis ex rhoncus, vitae fringilla velit feugiat. Quisque condimentum mi et ligula hendrerit, at congue dui accumsan. Nam faucibus arcu id risus suscipit, eget iaculis dolor cursus. Mauris eget massa eget dui suscipit vulputate quis maximus tellus. Sed blandit odio nisi, a condimentum leo porttitor at. Nam metus enim, condimentum semper auctor id, accumsan non sapien. Maecenas enim lacus, aliquam nec libero id, suscipit dictum mauris. Aliquam erat volutpat. Mauris sodales ante nisl, a aliquet enim facilisis et. Morbi quis felis vitae augue ornare lobortis.
Donec rutrum rutrum tempus. Fusce ac justo et orci tempor dignissim consectetur euismod ligula. Curabitur tempor sapien erat. Mauris nisl lorem, vulputate id volutpat vitae, vulputate a est. Nullam non augue at lectus mattis gravida. Phasellus vestibulum scelerisque erat at scelerisque. Nullam at erat euismod, egestas arcu in, condimentum lorem. Proin nec cursus magna. Sed pretium egestas quam nec ultrices. Nullam nulla lorem, dapibus eget eros sed, interdum posuere lacus. Nulla tincidunt malesuada interdum. Suspendisse a pellentesque sem. Nunc ultrices, dolor quis feugiat vestibulum, nisi velit venenatis nisl, nec convallis nisl eros eu nunc. Sed molestie finibus blandit. Aenean malesuada tincidunt lectus, in maximus dui.
Donec lacinia sem mollis quam tempor scelerisque. Etiam tincidunt facilisis bibendum. Phasellus dignissim vulputate turpis, porta aliquet magna auctor non. Fusce dignissim eget justo at elementum. Cras elit dolor, mattis nec sapien eu, ultrices dapibus metus. Donec in tempor nibh, vitae porttitor quam. Donec vitae risus sed nulla mattis pellentesque. Nulla metus nisi, venenatis sit amet leo vel, lacinia auctor nisi.
Nunc accumsan odio eget lectus varius, eget malesuada tellus iaculis. Nam elementum est dolor, eu ullamcorper nibh hendrerit ac. Phasellus turpis velit, aliquet eu condimentum vitae, vehicula non purus. Nunc et feugiat dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ante ex, pulvinar et sapien at, aliquet euismod diam. Etiam nunc dolor, gravida quis risus eget, accumsan consequat magna. Maecenas viverra imperdiet mauris. Etiam ac massa sapien. Maecenas cursus sodales commodo. Vivamus eget libero id metus volutpat accumsan in vitae tellus. Vivamus venenatis neque eu tellus ultricies, id scelerisque neque lobortis. Aliquam iaculis risus erat, ut maximus tellus luctus at.
Vestibulum laoreet interdum risus, mollis iaculis tortor sagittis sit amet. Integer in lacus feugiat, convallis ligula vitae, porttitor mi. Praesent molestie molestie leo, vitae aliquam nisi consequat ac. Donec venenatis lorem condimentum, tincidunt tortor eget, pellentesque massa. Sed eget consequat ante. Suspendisse eget eleifend eros. Proin ac posuere nulla. In tristique non lectus in feugiat. Sed blandit tincidunt nulla, a mollis quam. Quisque non risus volutpat, sagittis nunc et, consequat lorem. Sed consectetur feugiat hendrerit. Sed consectetur gravida imperdiet.
Aliquam imperdiet massa non dui consequat, et molestie tellus fermentum. Proin a lacus eget nunc hendrerit gravida vel cursus lacus. Sed augue lorem, egestas viverra ornare sed, dictum nec ante. Donec sodales ante ac imperdiet pretium. Nullam congue mauris non eleifend auctor. Cras dapibus finibus dictum. Quisque neque urna, dignissim at sem bibendum, ultricies porttitor odio. Fusce finibus odio sed nisi pretium, maximus pellentesque risus efficitur. Suspendisse volutpat elit at nisi malesuada dapibus. Ut venenatis libero massa, in consequat lectus rhoncus non. Cras posuere in libero eu suscipit. Sed suscipit quis nibh vel dapibus. Nam ut turpis nec libero rhoncus pellentesque.
Pellentesque quis vehicula neque, eget scelerisque tellus. Praesent vulputate tincidunt sapien nec maximus. Donec a felis lorem. Pellentesque augue turpis, facilisis in ullamcorper eu, pulvinar et tortor. Mauris eget rutrum felis. Integer vel neque massa. Mauris dui neque, commodo ut venenatis eu, vehicula at purus. Suspendisse eu sodales dolor. In hac habitasse platea dictumst. Nulla varius sapien eget metus suscipit gravida. Sed feugiat aliquam lectus, quis pretium nisl sodales vitae. Duis at dolor accumsan, iaculis ipsum eget, maximus sapien. Nam auctor, orci non placerat sollicitudin, elit quam imperdiet turpis, eget lacinia velit turpis vitae massa. Phasellus facilisis tincidunt pellentesque.
Proin congue, odio id mattis ultrices, mauris nulla pulvinar sapien, eget malesuada velit magna vel quam. Sed risus quam, luctus in urna id, sollicitudin egestas nibh. Sed eu pulvinar diam. Aliquam in sapien sit amet odio tempus rhoncus. In ac posuere justo. Quisque eleifend velit scelerisque faucibus varius. Pellentesque laoreet eros sed urna luctus fermentum. Nulla mattis turpis nec dictum euismod. Fusce ligula massa, ultrices a dictum id, elementum sed urna. Donec viverra arcu neque, quis sollicitudin odio condimentum vel. Cras laoreet interdum finibus. Sed eleifend ultricies purus, et rhoncus orci dignissim eget.
Sed quis pretium risus. Aenean placerat erat risus, nec sodales erat egestas quis. Suspendisse mi velit, dictum sit amet maximus sed, hendrerit sit amet elit. Aliquam viverra facilisis magna non pretium. Aenean laoreet placerat fermentum. Suspendisse iaculis erat sed vehicula laoreet. In vel ex vel neque tristique volutpat sed cursus mauris. Mauris scelerisque pharetra libero, at malesuada sapien consequat quis. Donec vehicula ultricies risus, a tristique sapien laoreet ut. Curabitur accumsan mi sed nibh laoreet tempor. Aliquam feugiat elit quis lorem eleifend, tristique eleifend felis tincidunt.
Cras sit amet luctus ex, lacinia pharetra odio. Donec non ex lobortis, varius eros eget, pulvinar orci. Mauris egestas ullamcorper massa quis cursus. Phasellus non nulla risus. Suspendisse sit amet metus cursus, aliquam erat id, scelerisque odio. Donec luctus purus ac risus lacinia, nec malesuada orci lacinia. Fusce hendrerit blandit eros et viverra. In at erat luctus, tristique erat in, ultrices elit. Ut euismod, neque quis volutpat congue, neque mauris interdum arcu, at venenatis ipsum sem sit amet felis. Fusce tempus, neque eu aliquet auctor, ipsum risus accumsan lacus, id dignissim metus ex non erat. Donec ornare enim non elementum pulvinar. Ut feugiat aliquam mauris a vestibulum. Integer tempus, mauris nec accumsan congue, velit lectus pretium risus, vel blandit ante quam gravida urna. Aliquam sed feugiat orci. Nunc sollicitudin lorem vitae euismod commodo.
Vestibulum eget lacus quis enim tincidunt venenatis. Nullam elementum eros nec eros elementum eleifend. Integer bibendum ut neque fringilla molestie. Cras vel purus lorem. Donec sed posuere mi. Fusce efficitur urna nec nibh suscipit mattis. Curabitur mattis pulvinar viverra. Donec ut urna arcu. Sed tempus magna ipsum, posuere malesuada libero vulputate vel.
Duis a rhoncus nisi. Nam vehicula maximus auctor. Nulla eu enim sit amet nunc efficitur vestibulum. Nulla eros quam, gravida id auctor et, faucibus non magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Ut posuere mi ut justo varius, non pretium justo condimentum. Maecenas nec ipsum quis ante sollicitudin cursus. Ut eget tortor id risus laoreet laoreet eu sed quam.
Aenean non aliquet arcu. Integer et interdum libero, posuere rutrum nulla. Vestibulum malesuada diam mi, eget gravida nulla finibus non. Ut sit amet erat in augue consequat finibus rhoncus ut velit. Mauris justo quam, molestie in sem a, rutrum efficitur odio. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed varius pellentesque imperdiet. Nulla tempus imperdiet semper.
Nulla viverra diam et viverra tempus. Etiam eleifend lectus lacus, a sollicitudin lacus porta in. Nam vulputate a augue quis molestie. Vivamus pellentesque purus nec tellus imperdiet, et commodo elit dapibus. Donec dolor nisi, convallis non orci et, porttitor maximus mauris. Pellentesque et leo fringilla, blandit nisi nec, pellentesque ligula. Morbi id finibus felis. Pellentesque nec mi tempus, tempus urna ut, posuere eros. Sed finibus vitae quam sed vestibulum. Proin mauris massa, maximus eu mi vel, ornare imperdiet est. Proin eu pharetra ex, eget placerat purus. In congue urna a elit porta, et placerat magna faucibus. Etiam vitae molestie odio, ut euismod justo.
Etiam maximus massa in egestas accumsan. Curabitur ac rutrum felis. Aenean non laoreet nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus. Maecenas id neque quam. Fusce semper facilisis venenatis. Donec a lacus egestas, malesuada mi id, efficitur nisl. Nullam augue ante, iaculis non faucibus sit amet, lobortis sed lorem. Sed ultricies libero sit amet lectus porta, ut maximus nulla placerat. Nulla ac mattis sem. Pellentesque nec posuere elit, in varius est. Suspendisse dictum est sed massa facilisis, eget scelerisque nibh lacinia. Integer aliquet mauris vel erat mollis vulputate.
Sed non sodales ipsum. Phasellus elit erat, sagittis et eros nec, mattis condimentum felis. Nulla vitae neque nulla. Aliquam ac felis turpis. Suspendisse nec diam quis turpis tincidunt posuere. Mauris eu dapibus magna, sit amet tincidunt odio. Nulla ac enim sit amet lorem pulvinar fringilla ac et sapien. Sed et pharetra enim. Proin quis laoreet nisi. Sed at purus quis quam venenatis tincidunt. Proin condimentum, nunc et tincidunt accumsan, sem erat elementum nisl, id vulputate lorem purus id leo. Mauris suscipit gravida turpis, a lacinia diam consequat ac. Vivamus semper egestas lectus. Sed commodo ante ac elit efficitur euismod.
In a ornare quam, non gravida tortor. Phasellus hendrerit ipsum eu rutrum fermentum. Maecenas vulputate efficitur condimentum. Donec venenatis maximus dictum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed porttitor faucibus nisl, sit amet volutpat magna aliquet vitae. Ut ultricies massa vel magna convallis, at condimentum nulla amet.`
  })

  it('must serialize and parse using hex', () => {
    const script1 = new Script([
      Ops.OP_FALSE,
      Ops.OP_RETURN,
      b512,
      b66000
    ])

    const hex = script1.toHex()
    const script2 = Script.fromHex(hex)
    
    assert.lengthOf(script2.chunks, 4)
    assert.equal(script2.chunks[2].toString(), b512)
    assert.equal(script2.chunks[3].toString(), b66000)
  })

  it('must serialize and parse using ASM', () => {
    const script1 = new Script([
      Ops.OP_FALSE,
      Ops.OP_RETURN,
      b512,
      b66000
    ])

    const asm = script1.toASM()
    const script2 = Script.fromASM(asm)
    
    assert.lengthOf(script2.chunks, 4)
    assert.equal(script2.chunks[2].toString(), b512)
    assert.equal(script2.chunks[3].toString(), b66000)
  })
})
